version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Building Docker image
      - docker build -t mi-app ./app
artifacts:
  files:
    - '**/*'
